server:
  port: 8081
  host: localhost
  name: server-management
  version: 1.0
  mode: development

db:
  port: 5432
  host: localhost
  username: postgres
  password: postgres
  db_name: management_system

jwt:
  signing_key: zDgKZG9vVZGFumVP5fQQMwMmN7EGsHY7mDKFyF59V9CrbVVm2GXdYjXYSHXAwB9KRSUhN3mhqUPVm9fg4RKq72B6tArYGZEBK5TT6FdqGMtYYhXjSkCBQtZjvaHjemAW
  token_expiration: 60
  refresh_token_expiration: 7
  encryption_key: 447FC2AA6EFFFEE5405A559E88DC958C
